name: API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Newman
        run: npm install -g newman newman-reporter-html

      - name: Generate API token
        id: generate_token
        run: |
          TOKEN=$(curl -s -X POST https://testing.simple-grocery-store-api.click/api-clients \
            -H "Content-Type: application/json" \
            -d '{"clientName":"GH Actions","clientEmail":"actions@example.com"}' | jq -r '.accessToken')
          echo "ACCESS_TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Run API tests
        run: |
          newman run collections/simple_grocery.json \
          -e environments/testing_environment.json \
          --env-var "accessToken=$ACCESS_TOKEN" \
          -r cli,html \
          --reporter-html-export reports/report.html

      - uses: actions/upload-artifact@v4
        with:
          name: api-report
          path: reports/report.html
